WIN_WIDH = 576
WIN_HEIGHT = 324

COLOR_ORANGE= (255,128,0)
COLOR_WRITE= (255,255,255)

MENU_OPTION = ('NEW GAME 1P',
               'NEW GAME 2P - COOPERATIVE',
               'NEW GAME 2P - COOPERATIVE',
               'SCORE',
               'EXITE')
